// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

eshqs.wad
gfx/env/eshq_citday_bk.tga
gfx/env/eshq_citday_dn.tga
gfx/env/eshq_citday_ft.tga
gfx/env/eshq_citday_lf.tga
gfx/env/eshq_citday_rt.tga
gfx/env/eshq_citday_up.tga
hlclassic/items/guncock1.wav
maps/eshq02.res
maps/eshqglobal.gmr
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/eshq/enemi/apache.mdl
models/eshq/enemi/apachet.mdl
models/eshq/enemi/barney.mdl
models/eshq/enemi/gman.mdl
models/eshq/enemi/hassassin.mdl
models/eshq/enemi/hassassinf.mdl
models/eshq/enemi/hgrunt.mdl
models/eshq/enemi/scientist.mdl
models/eshq/objects/bath.mdl
models/eshq/objects/bed.mdl
models/eshq/objects/bigspiggot.mdl
models/eshq/objects/bookgibs.mdl
models/eshq/objects/kitchensink.mdl
models/eshq/objects/toilet.mdl
models/eshq/p_357.mdl
models/eshq/p_9mmar.mdl
models/eshq/p_9mmhandgun.mdl
models/eshq/p_crossbow.mdl
models/eshq/p_crowbar.mdl
models/eshq/p_egon.mdl
models/eshq/p_gauss.mdl
models/eshq/p_grenade.mdl
models/eshq/p_hgun.mdl
models/eshq/p_rpg.mdl
models/eshq/p_satchel.mdl
models/eshq/p_satchel_radio.mdl
models/eshq/p_shotgun.mdl
models/eshq/p_squeak.mdl
models/eshq/p_tripmine.mdl
models/eshq/v_357.mdl
models/eshq/v_9mmar.mdl
models/eshq/v_9mmhandgun.mdl
models/eshq/v_crossbow.mdl
models/eshq/v_crowbar.mdl
models/eshq/v_desert_eagle.mdl
models/eshq/v_displacer.mdl
models/eshq/v_egon.mdl
models/eshq/v_gauss.mdl
models/eshq/v_grenade.mdl
models/eshq/v_hgun.mdl
models/eshq/v_m40a1.mdl
models/eshq/v_medkit.mdl
models/eshq/v_pipe_wrench.mdl
models/eshq/v_rpg.mdl
models/eshq/v_satchel.mdl
models/eshq/v_satchel_radio.mdl
models/eshq/v_saw.mdl
models/eshq/v_shotgun.mdl
models/eshq/v_spore_launcher.mdl
models/eshq/v_squeak.mdl
models/eshq/v_tripmine.mdl
models/eshq/v_uzi.mdl
models/eshq/w_357.mdl
models/eshq/w_9mmar.mdl
models/eshq/w_9mmhandgun.mdl
models/eshq/w_crossbow.mdl
models/eshq/w_crowbar.mdl
models/eshq/w_egon.mdl
models/eshq/w_gauss.mdl
models/eshq/w_grenade.mdl
models/eshq/w_hgun.mdl
models/eshq/w_rpg.mdl
models/eshq/w_satchel.mdl
models/eshq/w_shotgun.mdl
models/eshq/w_sqknest.mdl
models/eshq/w_squeak.mdl
sound/eshqvoice/ambience/aliencave1.wav
sound/eshqvoice/ambience/drips.wav
sound/eshqvoice/ambience/electramb1.wav
sound/eshqvoice/ambience/industrial1.wav
sound/eshqvoice/ambience/mechwhine.wav
sound/eshqvoice/ambience/warn1.wav
sound/eshqvoice/ambience/warn2.wav
sound/eshqvoice/ambience/warn9.wav
sound/eshqvoice/eshq_sentences.txt
sound/eshqvoice/gman/m02f01.wav
sprites/hl_weapons/weapon_hl357.txt
