// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

eshqs.wad
gfx/env/eshq_citday_bk.tga
gfx/env/eshq_citday_dn.tga
gfx/env/eshq_citday_ft.tga
gfx/env/eshq_citday_lf.tga
gfx/env/eshq_citday_rt.tga
gfx/env/eshq_citday_up.tga
gfx/env/eshq_seaeve_bk.tga
gfx/env/eshq_seaeve_dn.tga
gfx/env/eshq_seaeve_ft.tga
gfx/env/eshq_seaeve_lf.tga
gfx/env/eshq_seaeve_rt.tga
gfx/env/eshq_seaeve_up.tga
maps/eshq01.bsp
maps/eshq01.res
maps/eshq02.bsp
maps/eshq02.res
maps/eshq03.bsp
maps/eshq03.res
maps/eshq04.res
maps/eshq05.bsp
maps/eshq05.res
maps/eshq06.bsp
maps/eshq06.res
maps/eshq07.bsp
maps/eshq07.res
maps/eshq08.bsp
maps/eshq08.res
maps/eshq09.bsp
maps/eshq09.res
maps/eshqglobal.gmr
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/eshq/enemi/apache.mdl
models/eshq/enemi/apachet.mdl
models/eshq/enemi/gman.mdl
models/eshq/enemi/hassassin.mdl
models/eshq/enemi/hassassinf.mdl
models/eshq/enemi/hgruntv1_.mdl
models/eshq/enemi/hgruntv1_01.mdl
models/eshq/enemi/hgruntv1_02.mdl
models/eshq/enemi/hgruntv1_03.mdl
models/eshq/enemi/pit_drone.mdl
models/eshq/enemi/zombie2.mdl
models/eshq/objects/bath.mdl
models/eshq/objects/bed.mdl
models/eshq/objects/bigspiggot.mdl
models/eshq/objects/bookgibs.mdl
models/eshq/objects/kitchensink.mdl
models/eshq/objects/simplecar.mdl
models/eshq/objects/simplefork.mdl
models/eshq/objects/simplejeep.mdl
models/eshq/objects/simplepolice.mdl
models/eshq/objects/toilet.mdl
models/eshq/p_357.mdl
models/eshq/p_9mmar.mdl
models/eshq/p_9mmhandgun.mdl
models/eshq/p_crossbow.mdl
models/eshq/p_crowbar.mdl
models/eshq/p_egon.mdl
models/eshq/p_gauss.mdl
models/eshq/p_grenade.mdl
models/eshq/p_hgun.mdl
models/eshq/p_rpg.mdl
models/eshq/p_satchel.mdl
models/eshq/p_satchel_radio.mdl
models/eshq/p_shotgun.mdl
models/eshq/p_squeak.mdl
models/eshq/p_tripmine.mdl
models/eshq/v_357.mdl
models/eshq/v_9mmar.mdl
models/eshq/v_9mmhandgun.mdl
models/eshq/v_crossbow.mdl
models/eshq/v_crowbar.mdl
models/eshq/v_desert_eagle.mdl
models/eshq/v_displacer.mdl
models/eshq/v_egon.mdl
models/eshq/v_gauss.mdl
models/eshq/v_grenade.mdl
models/eshq/v_hgun.mdl
models/eshq/v_m40a1.mdl
models/eshq/v_medkit.mdl
models/eshq/v_pipe_wrench.mdl
models/eshq/v_rpg.mdl
models/eshq/v_satchel.mdl
models/eshq/v_satchel_radio.mdl
models/eshq/v_saw.mdl
models/eshq/v_shotgun.mdl
models/eshq/v_spore_launcher.mdl
models/eshq/v_squeak.mdl
models/eshq/v_tripmine.mdl
models/eshq/v_uzi.mdl
models/eshq/w_357.mdl
models/eshq/w_9mmar.mdl
models/eshq/w_9mmhandgun.mdl
models/eshq/w_crossbow.mdl
models/eshq/w_crowbar.mdl
models/eshq/w_egon.mdl
models/eshq/w_gauss.mdl
models/eshq/w_grenade.mdl
models/eshq/w_hgun.mdl
models/eshq/w_rpg.mdl
models/eshq/w_satchel.mdl
models/eshq/w_shotgun.mdl
models/eshq/w_sqknest.mdl
models/eshq/w_squeak.mdl
sound/eshqvoice/ambience/aliencave1.wav
sound/eshqvoice/ambience/alienlaser1.wav
sound/eshqvoice/ambience/bigexplosion1.wav
sound/eshqvoice/ambience/burning1.wav
sound/eshqvoice/ambience/clank1.wav
sound/eshqvoice/ambience/computalk2.wav
sound/eshqvoice/ambience/crtnoise.wav
sound/eshqvoice/ambience/drips.wav
sound/eshqvoice/ambience/electramb1.wav
sound/eshqvoice/ambience/flies.wav
sound/eshqvoice/ambience/generator3.wav
sound/eshqvoice/ambience/industrial1.wav
sound/eshqvoice/ambience/industrial2.wav
sound/eshqvoice/ambience/labdrone1.wav
sound/eshqvoice/ambience/mechwhine.wav
sound/eshqvoice/ambience/pounder.wav
sound/eshqvoice/ambience/rocketrumble1.wav
sound/eshqvoice/ambience/screammachine.wav
sound/eshqvoice/ambience/signalgear1.wav
sound/eshqvoice/ambience/signalgear2.wav
sound/eshqvoice/ambience/sparks.wav
sound/eshqvoice/ambience/warn1.wav
sound/eshqvoice/ambience/warn10.wav
sound/eshqvoice/ambience/warn2.wav
sound/eshqvoice/ambience/warn3.wav
sound/eshqvoice/ambience/warn4.wav
sound/eshqvoice/ambience/warn5.wav
sound/eshqvoice/ambience/warn8.wav
sound/eshqvoice/ambience/warn9.wav
sound/eshqvoice/ambience/wind2.wav
sound/eshqvoice/eshq_sentences.txt
sound/eshqvoice/gman/m01f01.wav
sound/eshqvoice/gman/m01f02.wav
sound/eshqvoice/gman/m02f01.wav
sound/eshqvoice/gman/m03f01.wav
sound/eshqvoice/gman/m05a01.wav
sound/eshqvoice/gman/m05f01.wav
sound/eshqvoice/gman/m05f02.wav
sound/eshqvoice/gman/m05f03.wav
sound/eshqvoice/gman/m05f04.wav
sound/eshqvoice/gman/m05f05.wav
sound/eshqvoice/gman/m05f06.wav
sound/eshqvoice/gman/m05f07.wav
sound/eshqvoice/gman/m05f08.wav
sound/eshqvoice/gman/m08e01.wav
sound/eshqvoice/gman/m08e02.wav
sound/eshqvoice/gman/m08e03.wav
sound/eshqvoice/gman/m08e04.wav
sound/eshqvoice/gman/m08e05.wav
sound/eshqvoice/gman/m08e06.wav
sound/eshqvoice/gman/m08e07.wav
sound/eshqvoice/gman/m08e08.wav
sound/eshqvoice/gman/m09f01.wav
sprites/cubemath/weapon_debug.txt
sprites/hl_weapons/weapon_hl357.txt
