// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

eshqs.wad
gfx/env/eshq_seaeve_bk.tga
gfx/env/eshq_seaeve_dn.tga
gfx/env/eshq_seaeve_ft.tga
gfx/env/eshq_seaeve_lf.tga
gfx/env/eshq_seaeve_rt.tga
gfx/env/eshq_seaeve_up.tga
maps/eshq08.res
maps/eshqglobal.gmr
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/eshq/enemi/apache.mdl
models/eshq/enemi/apachet.mdl
models/eshq/enemi/gman.mdl
models/eshq/enemi/hassassin.mdl
models/eshq/enemi/hassassinf.mdl
models/eshq/enemi/hgruntv1_.mdl
models/eshq/enemi/hgruntv1_01.mdl
models/eshq/enemi/hgruntv1_02.mdl
models/eshq/enemi/hgruntv1_03.mdl
models/eshq/enemi/pit_drone.mdl
models/eshq/enemi/zombie2.mdl
models/eshq/enemi/zombie_soldier.mdl
sound/eshqvoice/ambience/clank1.wav
sound/eshqvoice/ambience/warn10.wav
sound/eshqvoice/ambience/warn8.wav
sound/eshqvoice/eshq_sentences.txt
sound/eshqvoice/gman/m08e01.wav
sound/eshqvoice/gman/m08e02.wav
sound/eshqvoice/gman/m08e03.wav
sound/eshqvoice/gman/m08e04.wav
sound/eshqvoice/gman/m08e05.wav
sound/eshqvoice/gman/m08e06.wav
sound/eshqvoice/gman/m08e07.wav
sound/eshqvoice/gman/m08e08.wav
sprites/cubemath/weapon_debug.txt
sprites/hl_weapons/weapon_hl357.txt
