// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

eshqs.wad
gfx/env/eshq_citday_bk.tga
gfx/env/eshq_citday_dn.tga
gfx/env/eshq_citday_ft.tga
gfx/env/eshq_citday_lf.tga
gfx/env/eshq_citday_rt.tga
gfx/env/eshq_citday_up.tga
maps/eshq02.res
maps/eshqglobal.gmr
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/eshq/enemi/apache.mdl
models/eshq/enemi/apachet.mdl
models/eshq/enemi/gman.mdl
models/eshq/enemi/hassassin.mdl
models/eshq/enemi/hassassinf.mdl
models/eshq/enemi/hgruntv1_.mdl
models/eshq/enemi/hgruntv1_01.mdl
models/eshq/enemi/hgruntv1_02.mdl
models/eshq/enemi/hgruntv1_03.mdl
models/eshq/enemi/pit_drone.mdl
models/eshq/enemi/zombie2.mdl
models/eshq/enemi/zombie_soldier.mdl
models/eshq/objects/bath.mdl
models/eshq/objects/bed.mdl
models/eshq/objects/bigspiggot.mdl
models/eshq/objects/bookgibs.mdl
models/eshq/objects/kitchensink.mdl
models/eshq/objects/toilet.mdl
sound/eshqvoice/ambience/aliencave1.wav
sound/eshqvoice/ambience/drips.wav
sound/eshqvoice/ambience/electramb1.wav
sound/eshqvoice/ambience/industrial1.wav
sound/eshqvoice/ambience/mechwhine.wav
sound/eshqvoice/ambience/warn1.wav
sound/eshqvoice/ambience/warn2.wav
sound/eshqvoice/ambience/warn9.wav
sound/eshqvoice/eshq_sentences.txt
sound/eshqvoice/gman/m02f01.wav
sprites/cubemath/weapon_debug.txt
sprites/hl_weapons/weapon_hl357.txt
