// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

eshqs.wad
gfx/env/eshq_citnig_bk.tga
gfx/env/eshq_citnig_dn.tga
gfx/env/eshq_citnig_ft.tga
gfx/env/eshq_citnig_lf.tga
gfx/env/eshq_citnig_rt.tga
gfx/env/eshq_citnig_up.tga
maps/eshq12_v10.res
maps/eshqglobal.gmr
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/eshq/enemi/hassassin.mdl
models/eshq/enemi/hassassinf.mdl
models/eshq/enemi/hgruntv1_.mdl
models/eshq/enemi/hgruntv1_01.mdl
models/eshq/enemi/hgruntv1_02.mdl
models/eshq/enemi/hgruntv1_03.mdl
models/eshq/enemi/pit_drone.mdl
models/eshq/enemi/zombie2.mdl
models/eshq/enemi/zombie_soldier.mdl
models/eshq/objects/simplevan.mdl
sound/eshqvoice/ambience/battleambient1.wav
sound/eshqvoice/ambience/clank1.wav
sound/eshqvoice/ambience/electramb1.wav
sound/eshqvoice/eshq_sentences.txt
sound/eshqvoice/gman/m01f01.wav
sound/eshqvoice/gman/m01f02.wav
sound/eshqvoice/gman/m02f01.wav
sound/eshqvoice/gman/m03f01.wav
sound/eshqvoice/gman/m05a01.wav
sound/eshqvoice/gman/m05f01.wav
sound/eshqvoice/gman/m05f02.wav
sound/eshqvoice/gman/m05f03.wav
sound/eshqvoice/gman/m05f04.wav
sound/eshqvoice/gman/m05f05.wav
sound/eshqvoice/gman/m05f06.wav
sound/eshqvoice/gman/m05f07.wav
sound/eshqvoice/gman/m05f08.wav
sound/eshqvoice/gman/m08e01.wav
sound/eshqvoice/gman/m08e02.wav
sound/eshqvoice/gman/m08e03.wav
sound/eshqvoice/gman/m08e04.wav
sound/eshqvoice/gman/m08e05.wav
sound/eshqvoice/gman/m08e06.wav
sound/eshqvoice/gman/m08e07.wav
sound/eshqvoice/gman/m08e08.wav
sound/eshqvoice/gman/m09f01.wav
sound/eshqvoice/gman/m10f01.wav
sound/eshqvoice/gman/m11f01.wav
sound/eshqvoice/gman/m11f02.wav
sound/eshqvoice/gman/m11f03.wav
sprites/cubemath/weapon_debug.txt
sprites/hl_weapons/weapon_hl357.txt
